name: Mirror dev branch to GitLab

on:
  push:
    branches:
      - dev  # Only mirror when 'dev' branch changes

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push dev branch to GitLab
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.cranecloud.io/2026-se4-final-year-projects/bse26-12/bloodlifesaver/bloodlifesaver.git
          git push gitlab dev --force
          # Add skip-ci message to avoid triggering GitLab CI
          git push gitlab dev -o ci.skip
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
