name: Mirror dev to GitLab

on:
  push:
    branches:
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.cranecloud.io/2026-se4-final-year-projects/bse26-12/bloodlifesaver/bloodlifesaver.git || true
          git push gitlab dev:dev --force
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}